---
openapi: 3.0.0
info:
  title: Stock Buy and Price
  description: Allows you buy and price stocks
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: stocks
    description: Operations available for stock information
paths:
  /buy:
    get:
      summary: get buy requests
      operationId: app.get_buy_stock
      description: Gets buy events given a current date
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
        - name: end_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
      responses:
        "200":
          description: Successfully returned a list of purchase items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BuyEvent"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /priceCheck:
    get:
      tags:
        - devices
      summary: get stock price requests
      operationId: app.get_stock_price
      description: Gets stock price events given a current date
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
        - name: end_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33Z
      responses:
        "200":
          description: Successfully returned a price events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PriceEvent"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /health:
    get:
      tags:
        - devices
      summary: gets the health
      operationId: app.get_health_check
      description: check the status of the site
      responses:
        "200":
          description: Successfully returned health
                    
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    BuyEvent:
      required:
        - buyDate
        - buyPrice
        - purchaseID
        - sellVolume
        - stockTicker
        - traceId
      type: object
      properties:
        stockTicker:
          type: string
          example: AMZN
        purchaseID:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        traceId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        sellVolume:
          minimum: 0
          type: integer
          format: int32
          example: 5
        buyPrice:
          type: number
          format: float
          example: 12.11
        buyDate:
          format: date-time
          example: 2022-09-08T10:09:22.001Z
    PriceEvent:
      required:
        - dateStartMonth
        - dateStartDay
        - dateSort
        - stockTicker
        - timespanLen
        - timespanUnit
        - traceId
      type: object
      properties:
        stockTicker:
          type: string
          example: AMZN
        timespanUnit:
          type: string
          example: day/week/month
        timespanLen:
          type: integer
          format: int32
          example: 30
        dateStartMonth:
          type: integer
          format: int32
          example: 07
        dateStartDay:
          type: integer
          format: int32
          example: 21
        dateSort:
          type: string
          example: asc/desc
        traceId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
