---
openapi: 3.0.0
info:
  title: Health API
  description: This API is for Health info
  version: 1.0.0
servers:
  - url: http://localhost:8120
tags:
  - name: stocks
    description: Operations available for stock information
paths:
  /health:
    get:
      tags:
        - devices
      summary: gets the health
      operationId: app.display_health_status
      description: check the status of the site
      responses:
        "200":
          description: successfully checked health
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/health_show"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    
components:
  schemas:
    health_show:
      required:
        - receiver
        - storage
        - processing
        - audit
      type: object
      properties:
        receiver:
          type: string
          example: Running
        storage:
          type: string
        processing:
          type: string
        audit:
          type: string
